export interface CommandArgumentSpec {
  name: string;
  type: "string" | "number" | "path" | "json";
  required: boolean;
  description: string;
}

export interface CommandOptionSpec {
  name: string;
  type: "boolean" | "string" | "number" | "path" | "enum";
  required?: boolean;
  description: string;
  enum?: string[];
  defaultValue?: string | number | boolean;
}

export interface CommandDescribeSpec {
  path: string;
  description: string;
  group: "root" | "config" | "context" | "hooks" | "memory" | "migrate" | "doc" | "session" | "artifact" | "harness" | "security";
  docSlug: string;
  relatedCommands: string[];
  stability: "read-only" | "mutating";
  mutating: boolean;
  supportsDryRun: boolean;
  supportsRawJsonInput: boolean;
  outputSchemaSummary: string[];
  arguments: CommandArgumentSpec[];
  options: CommandOptionSpec[];
  examples: string[];
}

const COMMAND_SPECS: CommandDescribeSpec[] = [
  {
    path: "init",
    description: "저장소를 판독하고 부족한 기초 문서를 보강한 뒤 control-plane을 부팅합니다.",
    group: "root",
    docSlug: "commands/init",
    relatedCommands: ["hooks install", "ingest", "status"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: [
      "executionMode",
      "repositoryMode",
      "strategy",
      "scan",
      "coverage",
      "maturity",
      "knowledgeMap[]",
      "actions",
      "bootstrap",
      "nextActions[]",
    ],
    arguments: [],
    options: [
      { name: "--cwd", type: "path", description: "대상 저장소 루트 또는 그 하위 경로" },
      { name: "--yes", type: "boolean", description: "질문 없이 기본값으로 초기화" },
      { name: "--non-interactive", type: "boolean", description: "질문 없이 기본값으로 초기화" },
      { name: "--mode", type: "enum", description: "초기화 모드", enum: ["auto", "empty", "existing", "monorepo", "docs-heavy"], defaultValue: "auto" },
      { name: "--strategy", type: "enum", description: "문서 생성 강도", enum: ["minimal", "balanced", "full"], defaultValue: "balanced" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 계획만 계산" },
      { name: "--merge-existing", type: "boolean", description: "기존 문서를 우선 재사용", defaultValue: true },
      { name: "--output", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "text" },
      { name: "--git-init", type: "boolean", description: "비대화형 모드에서 git 저장소 자동 초기화" },
    ],
    examples: [
      "ragit init --mode auto --strategy balanced --merge-existing",
      "ragit init --yes --git-init --output json",
      "ragit init --dry-run --output json",
    ],
  },
  {
    path: "log",
    description: "snapshot 기반 semantic history와 artifact-backed collaboration state를 함께 요약합니다.",
    group: "root",
    docSlug: "commands/log",
    relatedCommands: ["status", "ingest", "memory recall"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["revRange", "maxCount", "showMissing", "filters", "entries[].snapshot", "entries[].semantic", "redactionSummary"],
    arguments: [{ name: "revRange", type: "string", required: false, description: "선택적인 git revision range" }],
    options: [
      { name: "--max-count", type: "number", description: "최종 출력 entry 개수 제한" },
      { name: "--view", type: "enum", description: "출력 축소 수준", enum: ["minimal", "default", "full"], defaultValue: "default" },
      { name: "--type", type: "enum", description: "문서 타입 필터", enum: ["adr", "prd", "srs", "spec", "plan", "ddd", "glossary", "pbd"] },
      { name: "--path", type: "string", description: "repo 내부 glob 필터" },
      { name: "--show-missing", type: "boolean", description: "snapshot 없는 commit도 함께 표시" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "text" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit log --max-count 5",
      "ragit log HEAD~10..HEAD --show-missing --format json",
    ],
  },
  {
    path: "timeline",
    description: "append-only 협업 이벤트 ledger를 읽어 session/memory/harness/ingest 시간축을 요약합니다. semantic snapshot state는 `log`가 담당합니다.",
    group: "root",
    docSlug: "commands/timeline",
    relatedCommands: ["log", "status", "memory recall"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["filters", "summary", "events[]", "redactionSummary"],
    arguments: [],
    options: [
      { name: "--goal", type: "string", description: "goalId 필터" },
      { name: "--episode", type: "string", description: "episodeId 필터" },
      { name: "--session", type: "string", description: "sessionId 필터" },
      { name: "--kind", type: "enum", description: "이벤트 계열 필터", enum: ["session", "artifact", "memory", "harness", "ingest", "security"] },
      { name: "--since", type: "string", description: "ISO-8601 lower bound" },
      { name: "--until", type: "string", description: "ISO-8601 upper bound" },
      { name: "--max-count", type: "number", description: "최종 출력 event 개수 제한" },
      { name: "--view", type: "enum", description: "출력 축소 수준", enum: ["minimal", "default", "full"], defaultValue: "default" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "text" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit timeline --kind memory --max-count 10",
      "ragit timeline --session 20260410T101500Z-a1b2c3d4 --format json",
    ],
  },
  {
    path: "narrative",
    description: "snapshot/artifact/event를 합성해 self-contained HTML narrative report를 생성합니다.",
    group: "root",
    docSlug: "commands/narrative",
    relatedCommands: ["log", "timeline", "memory recall", "status"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: [
      "dryRun",
      "reportPath",
      "modelPath",
      "schemaVersion",
      "projectionPolicyVersion",
      "projectionMode",
      "headSha",
      "window.revRange",
      "window.maxCommits",
      "window.selectedSnapshotShas[]",
      "window.missingSnapshotCommits",
      "summary",
      "summary.freshnessCounts.fresh",
      "summary.freshnessCounts.suspect",
      "summary.freshnessCounts.stale",
      "warnings[]",
    ],
    arguments: [{ name: "revRange", type: "string", required: false, description: "선택적인 git revision range" }],
    options: [
      { name: "--max-commits", type: "number", description: "선택할 indexed snapshot commit 개수", defaultValue: 10 },
      { name: "--output", type: "path", description: "report 출력 경로" },
      { name: "--emit-model", type: "path", description: "versioned viewer-safe narrative model JSON 출력 경로" },
      { name: "--open", type: "boolean", description: "생성 후 기본 브라우저로 열기" },
      { name: "--dry-run", type: "boolean", description: "파일을 쓰지 않고 계획만 계산" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "text" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit narrative --format both",
      "ragit narrative HEAD~20..HEAD --max-commits 6 --output .ragit/reports/custom.html --emit-model .ragit/reports/custom.json",
      "ragit narrative --dry-run --format json",
    ],
  },
  {
    path: "drift",
    description: "현재 HEAD 기준으로 durable/memory/harness 지식 객체가 아직 믿을 만한지 판정합니다.",
    group: "root",
    docSlug: "commands/drift",
    relatedCommands: ["status", "doctor", "log", "timeline", "ingest"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["overallStatus", "counts", "filters", "baseline", "items[]"],
    arguments: [],
    options: [
      { name: "--scope", type: "enum", description: "평가 범위", enum: ["durable", "memory", "harness", "all"], defaultValue: "all" },
      { name: "--path", type: "string", description: "repo 내부 glob 필터" },
      { name: "--goal", type: "string", description: "goalId 필터" },
      { name: "--session", type: "string", description: "sessionId 필터" },
      { name: "--max-count", type: "number", description: "최종 출력 item 개수 제한" },
      { name: "--view", type: "enum", description: "출력 축소 수준", enum: ["minimal", "default", "full"], defaultValue: "default" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "text" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit drift --scope all --view default --format both",
      "ragit drift --scope harness --goal ep-auth-refresh --format json",
    ],
  },
  {
    path: "repair",
    description: "drift 결과를 기반으로 기존 복구 명령을 계획하거나 safe action만 적용합니다.",
    group: "root",
    docSlug: "commands/repair",
    relatedCommands: ["drift", "ingest", "harness verify", "doc refresh", "artifact review", "memory promote"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["mode", "summary", "filters", "drift", "plannedActions[]", "executedActions[]", "skippedActions[]", "warnings[]"],
    arguments: [],
    options: [
      { name: "--apply", type: "boolean", description: "safe action만 실제 실행" },
      { name: "--scope", type: "enum", description: "평가 범위", enum: ["durable", "memory", "harness", "all"], defaultValue: "all" },
      { name: "--path", type: "string", description: "repo 내부 glob 필터" },
      { name: "--goal", type: "string", description: "goalId 필터" },
      { name: "--session", type: "string", description: "sessionId 필터" },
      { name: "--max-count", type: "number", description: "최종 출력 item 개수 제한" },
      {
        name: "--action",
        type: "enum",
        description: "계획 또는 실행할 action 필터",
        enum: ["ingest", "doc-refresh", "artifact-review", "harness-verify", "harness-run", "memory-promote"],
      },
      { name: "--view", type: "enum", description: "출력 축소 수준", enum: ["minimal", "default", "full"], defaultValue: "default" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit repair --scope all --format json",
      "ragit repair --apply --action ingest --action harness-verify --format both",
    ],
  },
  {
    path: "security audit",
    description: "control-plane, store, durable docs, provider egress 관점에서 지식 상태 보안 posture를 점검합니다.",
    group: "security",
    docSlug: "commands/security/audit",
    relatedCommands: ["security purge", "doctor", "status", "ingest"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["summary", "summary.admissionBlocked", "summary.admissionQuarantined", "providerEgress", "findings[]"],
    arguments: [],
    options: [
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit security audit --format json",
      "ragit security audit --cwd /path/to/repo --format both",
    ],
  },
  {
    path: "security purge",
    description: "control-plane/store/cache/quarantine에서 보안 사고 대응용 sanitize rewrite 또는 삭제를 수행합니다.",
    group: "security",
    docSlug: "commands/security/purge",
    relatedCommands: ["security audit", "ingest", "doctor", "status"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["mode", "target", "planned[]", "rewritten[]", "deleted[]", "warnings[]"],
    arguments: [],
    options: [
      { name: "--target", type: "enum", description: "정리 범위", enum: ["control-plane", "store", "cache", "quarantine", "all"], defaultValue: "all" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 계획만 계산" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit security purge --target control-plane --dry-run --format json",
      "ragit security purge --target store --format both",
    ],
  },
  {
    path: "describe",
    description: "command contract와 지원 옵션을 설명합니다.",
    group: "root",
    docSlug: "commands/describe",
    relatedCommands: ["query", "context pack", "memory recall"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["command", "availableCommands[]", "spec"],
    arguments: [{ name: "commandPath", type: "string", required: true, description: "설명할 command path" }],
    options: [{ name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" }],
    examples: [
      "ragit describe query --format json",
      "ragit describe memory promote --format both",
    ],
  },
  {
    path: "doc create",
    description: "표준 문서 타입 문서를 생성합니다.",
    group: "doc",
    docSlug: "commands/doc/create",
    relatedCommands: ["doc refresh", "doc validate", "doc reconcile"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["dryRun", "docType", "path", "canonicalPath", "status", "usedTemplate", "reconcile"],
    arguments: [],
    options: [
      { name: "--type", type: "enum", description: "문서 타입", enum: ["adr", "prd", "srs", "spec", "plan", "ddd", "glossary", "pbd"], required: true },
      { name: "--title", type: "string", description: "문서 제목", required: true },
      { name: "--path", type: "path", description: "생성할 repo 상대 경로" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 계획만 계산" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit doc create --type adr --title \"Token Rotation Policy\"",
      "ragit doc create --type spec --title \"Auth API\" --dry-run --format json",
    ],
  },
  {
    path: "doc refresh",
    description: "표준 문서 계약에 맞게 문서를 비파괴 정합화합니다.",
    group: "doc",
    docSlug: "commands/doc/refresh",
    relatedCommands: ["doc create", "doc validate", "ingest"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["dryRun", "plannedFiles", "refreshedFiles", "unchangedFiles", "violationsBefore", "violationsAfter", "reconcile"],
    arguments: [],
    options: [
      { name: "--type", type: "enum", description: "문서 타입 필터", enum: ["adr", "prd", "srs", "spec", "plan", "ddd", "glossary", "pbd"] },
      { name: "--files", type: "string", description: "정합화 대상 glob" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 계획만 계산" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit doc refresh --type adr",
      "ragit doc refresh --files \"docs/**/*.md\" --dry-run --format json",
    ],
  },
  {
    path: "doc validate",
    description: "표준 문서 계약 위반을 검사합니다.",
    group: "doc",
    docSlug: "commands/doc/validate",
    relatedCommands: ["doc refresh", "doc reconcile", "ingest"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["checkedFiles", "tracked", "violations", "files[]"],
    arguments: [],
    options: [
      { name: "--type", type: "enum", description: "문서 타입 필터", enum: ["adr", "prd", "srs", "spec", "plan", "ddd", "glossary", "pbd"] },
      { name: "--all", type: "boolean", description: "전체 타입 검사" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit doc validate --all",
      "ragit doc validate --type pbd --format json",
    ],
  },
  {
    path: "doc reconcile",
    description: "기존 문서를 canonical 경로에 비파괴 매핑하고 인덱스를 기록합니다.",
    group: "doc",
    docSlug: "commands/doc/reconcile",
    relatedCommands: ["doc validate", "status", "init"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["dryRun", "indexPath", "status", "tracked", "violations", "lastReconciledAt"],
    arguments: [],
    options: [
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 계획만 계산" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit doc reconcile",
      "ragit doc reconcile --dry-run --format json",
    ],
  },
  {
    path: "config set",
    description: "설정 키를 업데이트합니다.",
    group: "config",
    docSlug: "commands/config/set",
    relatedCommands: ["init", "status", "doctor"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["stdoutMessage"],
    arguments: [
      { name: "key", type: "string", required: true, description: "업데이트할 설정 키" },
      { name: "value", type: "string", required: true, description: "설정할 값" },
    ],
    options: [{ name: "--cwd", type: "path", description: "대상 저장소 경로" }],
    examples: [
      "ragit config set output.format markdown",
      "ragit config set memory.recall_top_k 8",
    ],
  },
  {
    path: "hooks install",
    description: "ragit 관리 hook를 설치합니다.",
    group: "hooks",
    docSlug: "commands/hooks/install",
    relatedCommands: ["hooks status", "hooks uninstall", "ingest"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["dryRun", "root", "hooks[]"],
    arguments: [],
    options: [
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 설치 계획만 확인" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "text" },
    ],
    examples: [
      "ragit hooks install --dry-run --format json",
      "ragit hooks install --format text",
    ],
  },
  {
    path: "hooks uninstall",
    description: "ragit 관리 hook를 제거합니다.",
    group: "hooks",
    docSlug: "commands/hooks/uninstall",
    relatedCommands: ["hooks install", "hooks status", "ingest"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["dryRun", "root", "hooks[]"],
    arguments: [],
    options: [
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 제거 계획만 확인" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "text" },
    ],
    examples: [
      "ragit hooks uninstall --dry-run --format json",
      "ragit hooks uninstall --format text",
    ],
  },
  {
    path: "hooks status",
    description: "ragit 관리 hook 상태를 확인합니다.",
    group: "hooks",
    docSlug: "commands/hooks/status",
    relatedCommands: ["hooks install", "hooks uninstall", "status"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["dryRun", "root", "hooks[]"],
    arguments: [],
    options: [
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit hooks status --format json",
      "ragit hooks status --format both",
    ],
  },
  {
    path: "ingest",
    description: "문서를 인덱싱하고 snapshot manifest를 갱신합니다.",
    group: "root",
    docSlug: "commands/ingest",
    relatedCommands: ["hooks install", "status", "query"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: true,
    outputSchemaSummary: ["mode", "processed", "skipped", "masked", "commitSha", "manifestPath", "plannedFiles", "deletedDocumentIds", "docAuthority", "admission", "warnings"],
    arguments: [],
    options: [
      { name: "--input", type: "path", description: "JSON 입력 파일 경로 또는 -" },
      { name: "--all", type: "boolean", description: "전체 문서 인덱싱" },
      { name: "--since", type: "string", description: "지정 SHA 이후 변경분 인덱싱" },
      { name: "--files", type: "string", description: "특정 glob 인덱싱" },
      { name: "--path", type: "path", description: "반복 가능한 repo 상대 경로 타깃" },
      { name: "--scope", type: "enum", description: "인덱싱 범위", enum: ["durable", "all"], defaultValue: "durable" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 계획만 검증" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit ingest --all --format json",
      "ragit ingest --input ingest.json --dry-run",
    ],
  },
  {
    path: "query",
    description: "snapshot 범위에서 지식을 검색합니다.",
    group: "root",
    docSlug: "commands/query",
    relatedCommands: ["context pack", "memory recall", "describe"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: true,
    outputSchemaSummary: ["query", "snapshotSha", "hits[]", "redactionSummary"],
    arguments: [{ name: "question", type: "string", required: false, description: "검색 질문" }],
    options: [
      { name: "--input", type: "path", description: "JSON 입력 파일 경로 또는 -" },
      { name: "--top-k", type: "number", description: "검색 결과 개수", defaultValue: 5 },
      { name: "--scope", type: "enum", description: "검색 범위", enum: ["durable", "session", "harness", "evidence", "all"], defaultValue: "durable" },
      { name: "--at", type: "string", description: "조회할 snapshot SHA 또는 prefix" },
      { name: "--view", type: "enum", description: "출력 축소 수준", enum: ["minimal", "default", "full"], defaultValue: "default" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "both" },
    ],
    examples: [
      'ragit query "restore auth context" --format json',
      "ragit query --input query.json --view minimal",
    ],
  },
  {
    path: "status",
    description: "현재 저장소와 zvec 상태를 요약합니다.",
    group: "root",
    docSlug: "commands/status",
    relatedCommands: ["doctor", "ingest", "hooks status"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: [
      "branch",
      "head",
      "backend",
      "zvec",
      "supported_types",
      "docsAuthority",
      "knowledge",
      "events",
      "manifests",
      "embedding.configured",
      "embedding.store",
      "embedding.ready",
      "embedding.needsMigration",
      "security",
      "format",
    ],
    arguments: [],
    options: [
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit status --format json",
      "ragit status --format both",
    ],
  },
  {
    path: "doctor",
    description: "환경과 저장소 일관성을 진단합니다.",
    group: "root",
    docSlug: "commands/doctor",
    relatedCommands: ["status", "init", "ingest"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["checks[]", "hasFailure"],
    arguments: [],
    options: [
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "text" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit doctor --format both",
      "ragit doctor --format json",
    ],
  },
  {
    path: "context pack",
    description: "목표 기준 컨텍스트 패킷을 생성합니다.",
    group: "context",
    docSlug: "commands/context/pack",
    relatedCommands: ["query", "memory recall", "describe"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: true,
    outputSchemaSummary: ["goal", "snapshotSha", "budget", "usedTokens", "selectedHits", "hits[]", "redactionSummary"],
    arguments: [{ name: "goal", type: "string", required: false, description: "컨텍스트를 만들 목표" }],
    options: [
      { name: "--input", type: "path", description: "JSON 입력 파일 경로 또는 -" },
      { name: "--budget", type: "number", description: "토큰 예산", defaultValue: 1200 },
      { name: "--scope", type: "enum", description: "검색 범위", enum: ["durable", "session", "harness", "evidence", "all"], defaultValue: "durable" },
      { name: "--at", type: "string", description: "조회할 snapshot SHA 또는 prefix" },
      { name: "--view", type: "enum", description: "출력 축소 수준", enum: ["minimal", "default", "full"], defaultValue: "default" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "both" },
    ],
    examples: [
      'ragit context pack "implementation plan for auth" --budget 1200',
      "ragit context pack --input context-pack.json --view minimal --format json",
    ],
  },
  {
    path: "session materialize",
    description: "세션 대화와 도구 흔적에서 session artifact를 추출합니다.",
    group: "session",
    docSlug: "commands/session/materialize",
    relatedCommands: ["artifact review", "memory wrap", "harness capture"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: true,
    outputSchemaSummary: ["sessionId", "transcriptPath", "eventPath", "artifactIds", "dryRun", "admission", "warnings"],
    arguments: [],
    options: [
      { name: "--input", type: "path", required: true, description: "JSON 입력 파일 경로 또는 -" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 추출 결과만 검증" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit session materialize --input session.json --dry-run --format json",
      "ragit session materialize --input transcript.json",
    ],
  },
  {
    path: "artifact review",
    description: "artifact 상태를 reviewed/retracted/superseded/archived로 전이합니다.",
    group: "artifact",
    docSlug: "commands/artifact/review",
    relatedCommands: ["session materialize", "memory promote", "harness promote"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: true,
    outputSchemaSummary: ["updated", "dryRun", "warnings"],
    arguments: [],
    options: [
      { name: "--input", type: "path", required: true, description: "JSON 입력 파일 경로 또는 -" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 상태 전이만 검증" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit artifact review --input review.json --dry-run --format json",
      "ragit artifact review --input review.json",
    ],
  },
  {
    path: "harness capture",
    description: "하네스 자원을 local artifact로 캡처합니다.",
    group: "harness",
    docSlug: "commands/harness/capture",
    relatedCommands: ["harness verify", "harness promote", "session materialize"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: true,
    outputSchemaSummary: ["artifactIds", "suiteId", "dryRun", "admission", "warnings"],
    arguments: [],
    options: [
      { name: "--input", type: "path", required: true, description: "JSON 입력 파일 경로 또는 -" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 생성 결과만 검증" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit harness capture --input harness.json --dry-run --format json",
      "ragit harness capture --input harness.json",
    ],
  },
  {
    path: "harness promote",
    description: "reviewed harness artifact를 docs/harness 아래 durable 문서로 승격합니다.",
    group: "harness",
    docSlug: "commands/harness/promote",
    relatedCommands: ["artifact review", "harness verify", "ingest"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: true,
    outputSchemaSummary: ["createdFiles", "plannedFiles", "ingested", "dryRun", "admission", "warnings"],
    arguments: [],
    options: [
      { name: "--input", type: "path", required: true, description: "JSON 입력 파일 경로 또는 -" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 승격 결과만 검증" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit harness promote --input promote.json --dry-run --format json",
      "ragit harness promote --input promote.json",
    ],
  },
  {
    path: "harness pack",
    description: "suite 기준 에이전트용 하네스 패킷을 만듭니다.",
    group: "harness",
    docSlug: "commands/harness/pack",
    relatedCommands: ["harness verify", "query", "context pack"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["suiteId", "goal", "resources[]", "redactionSummary"],
    arguments: [{ name: "suiteRef", type: "string", required: true, description: "suite artifact id 또는 경로" }],
    options: [
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit harness pack art_harness_suite_xxx --format json",
      "ragit harness pack .ragit/artifacts/harness/suite/example.json",
    ],
  },
  {
    path: "harness verify",
    description: "suite 구조와 oracle/evidence binding을 검증합니다.",
    group: "harness",
    docSlug: "commands/harness/verify",
    relatedCommands: ["harness capture", "harness pack", "artifact review"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["suiteId", "checks[]", "hasFailure"],
    arguments: [],
    options: [
      { name: "--suite", type: "path", required: true, description: "suite artifact id 또는 JSON 경로" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit harness verify --suite art_harness_suite_xxx --format json",
      "ragit harness verify --suite .ragit/artifacts/harness/suite/example.json",
    ],
  },
  {
    path: "harness run",
    description: "suite를 로컬 command executor로 실행하고 deterministic rule로 평가합니다.",
    group: "harness",
    docSlug: "commands/harness/run",
    relatedCommands: ["harness verify", "harness pack", "timeline"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: true,
    outputSchemaSummary: ["runId", "suiteId", "runPath", "preflight", "summary", "caseResults[]", "admission", "warnings"],
    arguments: [],
    options: [
      { name: "--input", type: "path", required: true, description: "JSON 입력 파일 경로 또는 -" },
      { name: "--dry-run", type: "boolean", description: "실행 없이 preflight와 planned run만 검증" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit harness run --input harness-run.json --dry-run --format json",
      "ragit harness run --input harness-run.json",
    ],
  },
  {
    path: "memory wrap",
    description: "세션 상태를 working memory에 기록합니다.",
    group: "memory",
    docSlug: "commands/memory/wrap",
    relatedCommands: ["memory recall", "memory promote", "context pack"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: true,
    outputSchemaSummary: ["sessionId", "sessionPath", "currentPath", "openLoopsPath", "sourceHeadSha", "dryRun", "admission"],
    arguments: [],
    options: [
      { name: "--input", type: "path", required: true, description: "JSON 입력 파일 경로 또는 -" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 계획만 검증" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit memory wrap --input session-wrap.json",
      "ragit memory wrap --input - --dry-run --format json",
    ],
  },
  {
    path: "memory recall",
    description: "working memory와 snapshot retrieval을 합쳐 recall packet을 만듭니다.",
    group: "memory",
    docSlug: "commands/memory/recall",
    relatedCommands: ["memory wrap", "memory promote", "query"],
    stability: "read-only",
    mutating: false,
    supportsDryRun: false,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["goal", "constraints", "openLoops", "relatedDecisions", "retrievedHits", "nextActions", "redactionSummary"],
    arguments: [{ name: "goal", type: "string", required: true, description: "복원할 목표" }],
    options: [
      { name: "--view", type: "enum", description: "출력 축소 수준", enum: ["minimal", "default", "full"], defaultValue: "default" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "both" },
    ],
    examples: [
      'ragit memory recall "resume auth flow" --view minimal',
      'ragit memory recall "resume auth flow" --format json',
    ],
  },
  {
    path: "memory promote",
    description: "promotion candidate를 표준 문서 타입(canonical docs/{type}/)으로 승격합니다.",
    group: "memory",
    docSlug: "commands/memory/promote",
    relatedCommands: ["memory wrap", "memory recall", "ingest"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: true,
    outputSchemaSummary: ["createdFiles", "plannedFiles", "sourceHeadSha", "ingested", "dryRun", "admission", "warnings"],
    arguments: [],
    options: [
      { name: "--input", type: "path", required: true, description: "JSON 입력 파일 경로 또는 -" },
      { name: "--dry-run", type: "boolean", description: "쓰기 없이 계획만 검증" },
      { name: "--format", type: "enum", description: "출력 형식", enum: ["text", "json", "both"], defaultValue: "json" },
    ],
    examples: [
      "ragit memory promote --input promotion-batch.json",
      "ragit memory promote --input promotion-batch.json --dry-run --format json",
    ],
  },
  {
    path: "migrate embeddings",
    description: "현재 store를 target embedding provider contract로 재구성합니다.",
    group: "migrate",
    docSlug: "commands/migrate/embeddings",
    relatedCommands: ["status", "doctor", "ingest"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["mode", "currentContract", "targetContract", "manifests", "documents", "chunks", "migrationNeeded"],
    arguments: [],
    options: [
      { name: "--dry-run", type: "boolean", description: "마이그레이션 계획만 확인" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit migrate embeddings --dry-run",
      "ragit migrate embeddings",
    ],
  },
  {
    path: "migrate from-json-store",
    description: "legacy json store를 zvec 기반 저장소로 변환합니다.",
    group: "migrate",
    docSlug: "commands/migrate/from-json-store",
    relatedCommands: ["migrate from-sqlitevss", "status", "ingest"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["mode", "docs", "chunks", "snapshotSha"],
    arguments: [],
    options: [
      { name: "--dry-run", type: "boolean", description: "마이그레이션 계획만 확인" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit migrate from-json-store --dry-run",
      "ragit migrate from-json-store",
    ],
  },
  {
    path: "migrate from-sqlitevss",
    description: "sqlite-vss export를 zvec 기반 저장소로 변환합니다.",
    group: "migrate",
    docSlug: "commands/migrate/from-sqlitevss",
    relatedCommands: ["migrate from-json-store", "status", "ingest"],
    stability: "mutating",
    mutating: true,
    supportsDryRun: true,
    supportsRawJsonInput: false,
    outputSchemaSummary: ["mode", "docs", "chunks", "snapshotSha"],
    arguments: [],
    options: [
      { name: "--dry-run", type: "boolean", description: "마이그레이션 계획만 확인" },
      { name: "--cwd", type: "path", description: "대상 저장소 경로" },
    ],
    examples: [
      "ragit migrate from-sqlitevss --dry-run",
      "ragit migrate from-sqlitevss",
    ],
  },
];

const normalizePath = (value: string): string => value.trim().replace(/\s+/g, " ");

export const listCommandSpecs = (): CommandDescribeSpec[] => COMMAND_SPECS.map((spec) => ({
  ...spec,
  relatedCommands: [...spec.relatedCommands],
  outputSchemaSummary: [...spec.outputSchemaSummary],
  arguments: spec.arguments.map((argument) => ({ ...argument })),
  options: spec.options.map((option) => ({ ...option, enum: option.enum ? [...option.enum] : undefined })),
  examples: [...spec.examples],
}));

export const listDescribableCommands = (): string[] => COMMAND_SPECS.map((spec) => spec.path);

export const describeCommandPath = (path: string): CommandDescribeSpec => {
  const normalized = normalizePath(path);
  const match = COMMAND_SPECS.find((spec) => spec.path === normalized);
  if (!match) {
    throw new Error(`설명 가능한 command가 아닙니다: ${path}`);
  }
  return {
    ...match,
    relatedCommands: [...match.relatedCommands],
    outputSchemaSummary: [...match.outputSchemaSummary],
    arguments: match.arguments.map((argument) => ({ ...argument })),
    options: match.options.map((option) => ({ ...option, enum: option.enum ? [...option.enum] : undefined })),
    examples: [...match.examples],
  };
};
